# Generated by Django 4.2.7 on 2023-11-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sobrenome',
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmar_senha',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='senha',
            field=models.CharField(max_length=12),
        ),
    ]
