# Generated by Django 4.2.7 on 2023-11-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_sobrenome_user_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(default='', max_length=11, unique=True),
        ),
    ]
